language: node_js
node_js:
- '6'
env:
  global:
  - secure: tzTeiQXUhBR8ABOQr4GLyjb1/S4z1aS8HMdZYzv7xGUELBv3QHeLKhdGUZZLnlaekv6JnAIUWFfzLLEubR0lv/BHiGzbRMljGIrIx20uaIYbczw7KQ3x01nsfRPaqCGwEDNdFaQahLZcuLhczxgDlIuSNtjuOrj52YlSDuybHO8v5KVZXBdX3jx6/XZN50Kzgr5w36j8T1a/1s/Xp1SKnOluaKFwn8x4usbdUcvKjStT5Nox0bV7BXiqHdCpBeMwDId7sOKj9fN4B5yu4wCITzSpp/PEZvIiqNaiCE0/PlbksSRGhyEY+HjLIAwChu3jzvPUdx1QjZpAILIUlEFvHnx3cYVdUfaQ5xbJ0w3/RjBZoKtbPMVPfFi6sHCs6kqLWrSRjV+XP+D8keH19R2uNl+teEUeQk1k6ED6qyrAPaxvc/BTp6fKZ3xvxJ+CgAjcQT4jw1HJ2JEqUTU3hB2TQWRbT7kpxs8fiE4GXuKTMsWYSBhwjFlSzcsJgwujPHreZM3hzj0yeP3eag61RM6AM5lP0+9C5Sg+mouZIXuX9ffuR52yXFibhJgJGHkfVAtOLdO1Gof+3F68oXbwOJLa3bNuHrrMk9g7f37HfUFo8IXPbpI9enUfEHLt6lMKAv3RPYanKo97gtT4IfzbDBzdsP8exuh1R2lumM45nf1B0Q8=
  - secure: bgxXtgQk6/Ga5R81hbZFDQQYC9hdFVl+M6BLcCIzpk9WSGTSyUn0NZbZyRfrF3UcPMGmELMcDGcTlkF5VQjHSf3YtEITNm7C7ibzOIu3ItcjPJHJdi4sReBDnyZV7aop8kj4SYDuaRdL2yzSkkURwPpjuUg/q38N8AEbxASZOaJIT9sZ4vZXItDQyevVhl/tnTtJGut+BY2HppQfcL7HJpjXorzGxTqVGKqVMuH4Lo8Kzrr6QuHcajTUsjmo5++2fjTiZkO000Fai0y4MI63mHQJip4YwEW0LL2Q5cto8k8OCGkDGzuhY2hEYD6glrG+815qIFMRNHexXS8vWFY+03plTkp+8fb25oB3bcW8540KdCYim9ekzqzO0wIZTIUhJ36w8XTsAfrta6asJb8tJMNIpEeMJml7BimcLYIHsUHVJTnoZfLlfVCrBRRa3dDEbOp7pNgnijeVfTXocc/lfK2C9FPVBZXNS0GOGFm+skAyV2Ezy3FRU5fDBZ6eqGNEuJvWjcr6c5fRHxAHwba5Q381d6MMDctpQtQJS9RirV5ps7gaEbm2HQ3dhsfd8ilCeIa3aC+SKviFbf8Md6E8b/GCjpIFqivdI4xll6gUYi6YwbpI5QGuqJGLvkzowPQ3tvb5RPqrKnZ5b7+nsdjAdXyJ5Sk7L5NPk2O6hpPK/E8=

before_install:
  - sudo dpkg --add-architecture i386
  - wget https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
  - sudo apt-get update
  - sudo apt-get install winehq-stable

install:
  - npm install
  - ./node_modules/bower/bin/bower install

script:
  - wine --version
  - ./node_modules/gulp/bin/gulp.js release-travis
